export type INCREMENT = 'COUNTER::INCREMENT';
export type DECREMENT = 'COUNTER::DECREMENT';

export const INCREMENT: INCREMENT = 'COUNTER::INCREMENT';
export const DECREMENT: DECREMENT = 'COUNTER::DECREMENT';

export type ActionTypes = INCREMENT | DECREMENT;
